#!/usr/bin/env bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
# Name : onex
# Date : 1 November 2021
# Description : onex is a hacking tools installer and package manager for hacker's.
#
# New Name : HacKing
# New Date : 10 January 2022
# New Description : HacKing is a hacking tools installer and package manager for hacker's.
#
# Created: 10/01/2022
# Aouther: Global Anlominus RhytMix 2022
# Skils: Best Copyrigter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: ToAllWorldCreatorsHackingTools
# Location: Made With Love IN Israel
# Tool Name: HacKing
# Source: https://github.com/Anlominus/HacKing
#
# Main Menu:
#  [1] AnonSurf: Anonymity surfing
#  [2] WebHack: Web Analysis
#  [3] VulnHack: Vulnerability Analysis
#  [4] WireLess: Wireless Analysis
#  [5] InfoGath: Information Gathering
#  [6] Forensics: Forensics Analysis
#  [7] FramXploit: Exploit Frameworks
#  [8] RAT: RemoteAccess
#  [9] HasHack: Hashing & Enctyprt Decrypt
#  [10] PayLoads: Payloads and more
#  [11] XInstKits: Installer Kits
#
#
#     Algorithen:
#
#     #Banner
#     #VNumbers
#     #VColors
#     #VMenu
#     #ManBanner
#     #FMenu
#     #Misc
#
#
#
###############
#    Banner   #
###############
function Banner(){
echo ""
echo ""
echo "$red       ###############################################"
echo "       #     _   _            _  ___                 #"
echo "       #    | | | | __ _  ___| |/ (_)_ __   __ _     #"
echo "       #    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #"
echo "       #    |  _  | (_| | (__| . \| | | | | (_| |    #"
echo "       #    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #"
echo "       #                                   |___/     #"
echo "$red       ###############################################"
echo "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]\n\n"

}

##################
#    ManBanner   #
##################
function ManBanner(){
echo -e "$purple
                           .
                       ..',,'..
                     .',,,,,,,,,.
                    .',,,'..',,,,'.
                   .',,'.     .,,,'
                  .',,.        .,,,.
                 .',..           .,,.
                 .'.              ..,.
                 .                  .'
                ..    $green Aภl๏miuภuຮ $purple   .
                ..                   .
                ..                  ...
         ....''''.     $blue HacKing$purple     .','''....
       .',,,,,,,,'..               ..',,,,,,,,'.
      ...'',,,,,,,'...          ....',,,,,,,,'...
     ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
    ......'',,;;;:::cccllllooooooooooooollll:'.....
    .....'.'',,;;::ccloodxxxdddddddooooollll,.'....
    .......',,;;::clloddxkkkkxxxdddoooollllc,......
    .'''''',,;;::cclooooDATOS0000Oxoooollllc,.......
   ..'''',',;;::ccclllooodk0xdddddxdoollllcc,'''''...
  ........';;::ccclllooodddxkkkkkkxdollllcc:'.........
 ......  .':::ccllloooodddxxxddddoddolllcc::'..  ......
 ......:.;:::ccllloooodddxxxddddooooollcc::;'c,':......
  .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''.
"
echo -e "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]"
}

nc="\033[00m"
################
#    VColors   #
################
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
nc=""

#################
#    VNumbers   #
#################
n00="00"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n7="7"
n8="8"
n9="9"
n10="10"
n11="11"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"

##################
#    VTCOLOR     #
##################
c0="$red[$green$n00$red]$white"
c1="$red[$green$n1$red]$white"
c2="$red[$green$n2$red]$white"
c3="$red[$green$n3$red]$white"
c4="$red[$green$n4$red]$white"
c5="$red[$green$n5$red]$white"
c6="$red[$green$n6$red]$white"
c7="$red[$green$n7$red]$white"
c8="$red[$green$n8$red]$white"
c9="$red[$green$n9$red]$white"
c10="$red[$green$n10$red]$white"
c11="$red[$green$n11$red]$white"

logo="${yellow}
  ___  _ __   ___${red} __  __
${yellow} / _ \\| '_ \\ / _ ${red} \\ \\/ /
${yellow}| (_) | | | |  __/${red} >  <
${yellow} \___/|_| |_|\\___${red} /_/\_\\
"
prompt="${purple}[${blue}HacKing${cyan}@${blue}space${purple}]$"

# checking for system home dir
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

# checking for system bin dir
if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

# checking for configuration dir
if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

# configuration files
if [ -d $conf_dir/HacKing ]; then
  if [ -e $conf_dir/HacKing/data/tools.dat ]; then
    tools_data="$conf_dir/HacKing/data/tools.dat"
  fi
  if [ -e $conf_dir/HacKing/data/category.dat ]; then
    category_data="$conf_dir/HacKing/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

# checking for system root access
if [ `command -v sudo` ]; then
  sudo="sudo"
else
  sudo=""
fi

# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
  sudo=""
fi

# install tools
install() {
  # get tool alias name
  tool_name=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f1`
  # get tool package manager
  tool_installer=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url ~/$tool_name
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url ~/$tool_name
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${purple}'$tool_name' ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
  # wait for user any input
  echo "$prompt "
  read tmp_inp
}

# install category tools
install_category_tool() {
  # get tool alias name
  tool_name=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f1`
  # get tools package manager
  tool_installer=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
  # wait for user any input
  echo "$prompt "
  read tmp_inp
}

# list all tools from data
all_tools() {
  while true; do
    clear
    # get all tools data
    echo " ${red} ___
//___// ${yellow}All Tools
"
    for data in `grep "." $tools_data | sort -f | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
      # display tools name from data
      for tool in $data; do
        echo " ${green} $tool" | tr '|' ' ' | tr '@' ' '
      done
    done
    echo " ${green} 0 Back"
    echo "$prompt "
    read cmd
    # count total number of tools
    list=`grep -n "." $tools_data | wc -l`
    # process user input
    case ${cmd} in
      [1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9])
        if [ ${cmd} -le $list ]; then
          # install tools
          install ${cmd}
        else
          echo "${red}${cmd}: ${purple}invalid option!!"
          sleep 1
        fi
      ;;
      0|back|Back)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# category function
category() {
  while true; do
    clear
    # get all category data
    echo " ${red} ___
//___// ${yellow}Tool Category
"
    for data in `grep "." $category_data | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
      # display category alias name from data
      for category in $data; do
        echo " ${green} $category" | tr '|' ' ' | tr '@' ' '
      done
    done
    echo " ${green} 0 Back"
    echo "$prompt "
    read cmd
    # count total number of category
    list=`grep -n "." $category_data | wc -l`
    # process user input
    case ${cmd} in
      [1-9]|[1-9][0-9])
        if [ ${cmd} -le $list ]; then
          while [ true ]; do
            clear
            # display all tools of selected category
            category=`grep '.' $category_data | sed -n "${cmd} p" | cut -d"|" -f2`
            category_alias=`grep '.' $category_data | sed -n "${cmd} p" | cut -d"|" -f1`
            # get all tools data and display
            echo " ${red} ___
//___// ${yellow}$category_alias
"
            for data in `grep "." $tools_data | sort -f | sed -n "/$category/p" | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
              # display tools name from data
              for tool in $data; do
                echo " ${green} $tool" | tr '|' ' ' | tr '@' ' '
              done
            done
            echo " ${green} 0 Back"
            echo "$prompt "
            read tmp_cmd
            # count total number of tools in category
            list=`grep -n "." $tools_data | sed -n "/$category/p" | wc -l`
            # process user input
            case $tmp_cmd in
              [1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9])
                if [ $tmp_cmd -le $list ]; then
                  # install tools
                  install_category_tool $category $tmp_cmd
                else
                  echo "${red}$tmp_cmd: ${purple}invalid option!!"
                  sleep 1
                fi
              ;;
                0|back|Back)
                break
              ;;
              *)
                echo "${red}'$tmp_cmd': ${purple}invalid option!!"
                sleep 1
              ;;
            esac
          done
        else
          echo "${red}${cmd}: ${purple}invalid option!!"
          sleep 1
        fi
      ;;
      0|back|Back)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# update HacKing function
update() {
  while true; do
    clear
    echo "$logo"
    echo " ${nc}[1] ${green} Update${nc}"
    echo " ${nc}[0] ${green} Back"
    echo "$prompt "
    read cmd
    case ${cmd} in
      1)
        # check user is online or not
        wget -q --spider http://google.com
        if [ $? -eq 0 ]; then
          echo "${green}Updating ...${nc}"
          sleep 1
          if [ `command -v git` ]; then
            if [ $sudo ]; then
              $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              $sudo chmod +x ~/HacKing/install
              $sudo sh ~/HacKing/install
            else
              git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              chmod +x ~/HacKing/install
              sh ~/HacKing/install
            fi
          else
            if [ $sudo ]; then
              $sudo $pac install git -y
              $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              $sudo chmod +x ~/HacKing/install
              $sudo sh ~/HacKing/install
            else
              $pac install git -y
              git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              chmod +x ~/HacKing/install
              sh ~/HacKing/install
            fi
          fi
          echo "${green} HacKing updated !!${nc}"
          sleep 1
        else
          echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          sleep 1
        fi
      ;;
      0)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# about HacKing function
about() {
  clear
  echo "$logo"
  echo " ${yellow}HacKing ${red} v0.1${nc}"
  echo " HacKing is a library of"
  echo " hacking tools for termux"
  echo " and other linux distribution.\n"
  echo " ${red}Warning:${nc}"
  echo " We are not responsible for any misuse"
  echo " or damage caused by this program."
  echo " Use this tool at your own risk!"
  echo "$prompt "
  read tmp
}

# this is the main function
menu() {
  while true; do
    clear
    Banner
    tools=`grep -n '.' $tools_data | wc -l`
    # echo "$logo"
    echo " ${c1} ${green} All tools ${nc}(${red}$tools tools${nc})"
    echo " ${c2} ${green} Tools category"
    echo " ${c3} ${green} Update HacKing"
    echo " ${c4} ${green} About us\n"
    echo " ${c5} ${green} Exit\n"
    echo "$prompt "
    read cmd
    case ${cmd} in
      1)
        all_tools
      ;;
      2)
        category
      ;;
      3)
        update
      ;;
      4)
        about
      ;;
      5|exit|Exit)
        echo "${green}Exiting ....${nc}"
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;
    esac
  done
}


# list all tools from data
cli_list_all() {
  # get all tools data
  tool=`grep "." $tools_data | sort -f | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr '|' ' '`
  # display tools name from data
  echo "${green} $tool${nc}"
}

# category function
cli_category() {
  # get all category data
  for data in `grep "." $category_data | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
    # display category alias name from data
    for category in $data; do
      echo " ${green} $category${nc}" | tr '|' ' ' | tr '@' ' '
    done
  done
}

# update process
update_process() {
  # check file is downloaded or not
  if [ -e $home/HacKing/HacKing ]; then
    # removing old one
    if [ -e $bin/HacKing ]; then
      if [ -d $conf_dir/HacKing ]; then
        if [ $sudo ]; then
          $sudo rm -rf $bin/HacKing
          $sudo rm -rf $conf_dir/HacKing
        else
          rm -rf $bin/HacKing
          rm -rf $conf_dir/HacKing
        fi
      fi
    fi
  fi

  # updating HacKing
  if [ -e $home/HacKing/HacKing ]; then
    if [ $sudo ]; then
      $sudo mv -v $home/HacKing/HacKing $bin
      $sudo chmod +x $bin/HacKing
    else
      mv -v $home/HacKing/HacKing $bin
      chmod +x $bin/HacKing
    fi
  fi
  if [ -d $home/HacKing ]; then
    if [ $sudo ]; then
    $sudo mv -v $home/HacKing $conf_dir
    else
      mv -v $home/HacKing $conf_dir
    fi
  fi
}

# update HacKing function
cli_update() {
  # check user is online or not
  wget -q --spider http://google.com
  if [ $? -eq 0 ]; then
    echo "${green}Updating ...${nc}"
    sleep 1
    if [ `command -v git` ]; then
      if [ $sudo ]; then
        $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      else
        git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
       fi
    else
      if [ $sudo ]; then
        $sudo $pac install git -y
        $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      else
        $pac install git -y
        git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      fi
    fi
    echo "${nc}'HacKing' ${green} updated successfully !!${nc}"
  else
    echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
  fi
}

# cli install process
install_process() {
  # get tool alias name
  tool_name=`echo $1 | cut -d"|" -f1`
  # get tool package manager
  tool_installer=`echo $1 | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`echo $1 | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`echo $1 | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`echo $1 | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url ./$tool_name
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url ./$tool_name
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            # install tool dependency
            echo "${green}Installing ...${nc}"
            sleep 1
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${green}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o ""./$tool_pac""
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${green} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${green} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
}

# check tool is exists or not
cli_install() {
  # get tools data
  for data in `grep -i "^$1" $tools_data`; do
    # display tools name from data
    for tool in $data; do
      # convert to lower case and check tool name
      if [ `echo $tool | cut -d"|" -f1 | tr 'A-Z' 'a-z'` = `echo $1 | tr 'A-Z' 'a-z'` ]; then
        get_tool_data=$tool
      fi
    done
  done
  # check data exists or not
  if [ $get_tool_data ]; then
    install_process $get_tool_data
  else
    echo "${red}Sorry ${nc}: '$1' ${red} tool not found !!${nc}"
    similar=`grep -i "^$1" $tools_data | cut -d"|" -f1`
    if [ "$similar" ]; then
      echo "${blue}Did you mean${nc}:"
      echo -n "${green} "
      grep -i "^$1" $tools_data | cut -d"|" -f1
      echo -n "${nc}"
    fi
  fi
}

# search tool
cli_search() {
  # get tools data
  similar=`grep -i "^$1" $tools_data | cut -d"|" -f1`
  if [ "$similar" ]; then
    echo -n "${green}"
    grep -i "^$1" $tools_data | cut -d"|" -f1
    echo -n "${nc}"
  else
    echo "${red}Sorry ${nc}: '$1' ${red} tool not found !!${nc}"
  fi
}

# remove function
cli_remove() {
  # add remove tools functionality for remove tools data now it only uninstall HacKing.
  # removing HacKing only
  if [ -e $bin/HacKing ]; then
    if [ -d $conf_dir/HacKing ]; then
      if [ $sudo ]; then
        $sudo rm -rf $bin/HacKing
        $sudo rm -rf $conf_dir/HacKing
      else
        rm -rf $bin/HacKing
        rm -rf $conf_dir/HacKing
      fi
    fi
  fi
  # check HacKing removed or not
  if [ ! -e $bin/HacKing ]; then
    if [ ! -d $conf_dir/HacKing ]; then
      echo "${nc}'HacKing' : ${green} uninstalled successfully !!${nc}"
    fi
  fi
}

# cli mode
if [ $# -eq 1 ]; then
  case $1 in
    start)
      menu
    ;;
    list|-l)
      cli_list_all
    ;;
    update|-u)
      cli_update
    ;;
    remove|-r)
      cli_remove
    ;;
    help|-h)
      echo "${yellow}HacKing ${red} v0.1"
      echo "${nc}Usage ${nc}: ${yellow} HacKing ${nc}[option]... [toolname]...${nc}"
      echo "\n  ${blue}Option  \tDescription${nc}"
      echo "  -----------  \t--------------------"
      echo "  help, -h  \tdisplay this help."
      echo "  list, -l  \tlist all tools."
      echo "  list -a  \tlist all tools."
      echo "  -l a  \tlist all tools."
      echo "  install, -i  \tinstall any tools."
      echo "  search, -s  \tsearch tools."
      echo "  update, -u  \tupdate HacKing."
      echo "  start  \tstart HacKing menu mode."
    ;;
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
    ;;
  esac
elif [ $# -eq 2 ]; then
  case $1 in
    list|-l)
      case $2 in
        -a|a)
          cli_list_all
         ;;
        *)
          echo "${red}Sorry ${nc}: '$2' ${red} invalid option!!${nc}"
          echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
        ;;
      esac
    ;;
    install|-i)
      cli_install $2
    ;;
    search|-s)
      cli_search $2
    ;;
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
    ;;
  esac
else
  echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
fi
