#!/usr/bin/env bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
# Name : onex
# Date : 1 November 2021
# Description : onex is a hacking tools installer and package manager for hacker's.
#
# New Name : HacKing
# New Date : 10 January 2022
# New Description : HacKing is a hacking tools installer and package manager for hacker's.
#
# Created: 10/01/2022
# Aouther: Global Anlominus RhytMix 2022
# Skils: Best Copyrigter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: ToAllWorldCreatorsHackingTools
# Location: Made With Love IN Israel
# Tool Name: HacKing
# Source: https://github.com/Anlominus/HacKing
#
# Main Menu:
#  [1] AnonSurf: Anonymity surfing
#  [2] WebHack: Web Analysis
#  [3] VulnHack: Vulnerability Analysis
#  [4] WireLess: Wireless Analysis
#  [5] InfoGath: Information Gathering
#  [6] Forensics: Forensics Analysis
#  [7] FramXploit: Exploit Frameworks
#  [8] RAT: RemoteAccess
#  [9] HasHack: Hashing & Enctyprt Decrypt
#  [10] PayLoads: Payloads and more
#  [11] XInstKits: Installer Kits
#
#
#     Algorithen:
#
#     #Banner
#     #VNumbers
#     #VColors
#     #VMenu
#     #ManBanner
#     #FMenu
#     #Misc
#
#
#
################
#    VColors   #
################
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
nc=""

###############
#    Banner   #
###############
function Banner(){
echo ""
echo ""
echo "$red       ###############################################"
echo "       #     _   _            _  ___                 #"
echo "       #    | | | | __ _  ___| |/ (_)_ __   __ _     #"
echo "       #    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #"
echo "       #    |  _  | (_| | (__| . \| | | | | (_| |    #"
echo "       #    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #"
echo "       #                                   |___/     #"
echo "$red       ###############################################"
echo "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]\n\n"

}
###############
#    Banner2   #
###############
function Banner2(){
echo "$VPrivEsc"
}

#################
#    VNumbers   #
#################
nx="x"
n00="00"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n7="7"
n8="8"
n9="9"
n10="10"
n11="11"
n12="12"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"

##################
#    VTCOLOR     #
##################
cSharp="$red[$yellow#$red]$white"
cInfo="$red[$yellow!$red]$white"
cPlus="$red[$green+$red]$white"
cx="$red[$green$nx$red]$cafe"
c1="$red[$green$n1$red]$cafe"
c2="$red[$green$n2$red]$cafe"
c3="$red[$green$n3$red]$cafe"
c4="$red[$green$n4$red]$cafe"
c5="$red[$green$n5$red]$cafe"
c6="$red[$green$n6$red]$cafe"
c7="$red[$green$n7$red]$cafe"
c8="$red[$green$n8$red]$cafe"
c9="$red[$green$n9$red]$cafe"
c10="$red[$green$n10$red]$cafe"
c11="$red[$green$n11$red]$cafe"
c12="$red[$green$n12$red]$cafe"
c13="$red[$green$n13$red]$cafe"
c14="$red[$green$n14$red]$cafe"
c15="$red[$green$n15$red]$cafe"
c16="$red[$green$n16$red]$cafe"
c17="$red[$green$n17$red]$cafe"
c18="$red[$green$n18$red]$cafe"

prompt="${purple}[${blue} Anlominus ${cyan}@${blue} HacKing ${purple}] $"
# checking for system home dir
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

# checking for system bin dir
if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

# checking for configuration dir
if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d ./data ]; then
  conf_dir="../"
fi

# configuration files
if [ -d $conf_dir/HacKing ]; then
  if [ -e $conf_dir/HacKing/data/tools.dat ]; then
    tools_data="$conf_dir/HacKing/data/tools.dat"
  fi
  if [ -e $conf_dir/HacKing/data/category.dat ]; then
    category_data="$conf_dir/HacKing/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

# checking for system root access
if [ `command -v sudo` ]; then
  sudo="sudo"
else
  sudo=""
fi

# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
  sudo=""
fi

menu() {
  while true; do
    clear
    Banner
    tools=`grep -n '.' $tools_data | wc -l`
    # echo "$logo"
    echo "\t ${c1} ${cafe} All Tools" ${red}[${purple}$tools${red} ]
    echo "\n\t ${c2} ${cafe} PrivEscLinux"
    echo "\t ${c3} ${cafe} Categories"
    echo "\t ${c4} ${cafe} Update"
    echo "\t ${c5} ${cafe} About\n"
    echo "\t ${cx} ${cafe} Exit\n"
    echo "  $prompt "
    read cmd
    case ${cmd} in
      1)
        all_tools
      ;;
      2)
        privEscLinux
      ;;
      3)
        category
      ;;
      4)
        update
      ;;
      5)
        about
      ;;
      x|0|00|exit|Exit)
        echo "${cafe}Exiting ...."
        clear
        exit
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;
    esac
  done
}

VPrivEsc="\n$red[$green+$red]$cyan Priviledge Escalation $red[$green+$red]\n"

# unix-privesc-check: Shell script to check for simple privilege escalation vectors on Unix systems

# Unix-Privilege-Escalation-Exploits-Pack: Exploits for getting local root on Linux, BSD, AIX, HP-UX, Solaris, RHEL, SUSE etc.

# uptux: Specialized privilege escalation checks for Linux systems.

privEscLinux() {
  while true; do
    clear
    Banner2
    echo "\t ${c1} ${cafe} AutoLocalPrivilegeEscalation:$cyan An automated script that download potential exploit for linux kernel from exploitdb, and compile them automatically."
    echo "\t ${c2} ${cafe} BeRoot:$cyan BeRoot Project is a post exploitation tool to check common misconfigurations to find a way to escalate our privilege. exploits."
    echo "\t ${c3} ${cafe} LinEnum:$cyan Scripted local Linux enumeration & privilege escalation checks"
    echo "\t ${c4} ${cafe} LinPEAS:$cyan Linux Privilege Escalation Awesome Script"
    echo "\t ${c5} ${cafe} Linux Exploit Suggester 2:$cyan Exploit suggester based on Linux_Exploit_Suggester"
    echo "\t ${c6} ${cafe} Linux Exploit Suggester:$cyan based on operating system release number."
    echo "\t ${c7} ${cafe} Linux Kernel Exploits"
    echo "\t ${c8} ${cafe} Linux PrivChecker:$cyan locally Linux enumerate system info, common privilege escalation, world writable files, misconfigurations, clear-text passwords and applicable exploits."
    echo "\t ${c9} ${cafe} Linux Smart Enumeration:$cyan Linux enumeration tools for pentesting and CTFs"
    echo "\t ${c10} ${cafe} Linux Soft Exploit Suggester:$cyan Linux enumeration tools for pentesting and CTFs"
    echo "\t ${c11} ${cafe} PrivEsc:$cyan collection of Windows, Linux and MySQL privilege escalation scripts and exploits."
    echo "\t ${c12} ${cafe} Lynis:$cyan Security auditing based on UNIX like$green Linux, macOS, BSD, and others."
    echo "\t ${c13} ${cafe} Pspy:$cyan Unprivileged Linux process snooping"
    echo "\t ${c14} ${cafe} Traitor:$cyan Automatically exploit low-hanging fruit to pop a root shell. Linux privilege escalation made easy!"
    echo "\t ${c15} ${cafe} Unix Privesc Check:$cyan Check for simple privilege escalation vectors on Unix systems"
    echo "\t ${c16} ${cafe} Unix Privilege Escalation Exploits Pack:$cyan Exploits for getting local root on$green Linux, BSD, AIX, HP-UX, Solaris, RHEL, SUSE etc."
    echo "\t ${c17} ${cafe} Uptux:$cyan Specialized privilege escalation checks for Linux systems."
    echo "\t ${c18} ${cafe} Cover My Ass:$cyan Cover your tracks on UNIX systems."
    echo "\t ${cx} ${cafe} Back\n"
    echo "  $prompt "
    read cmd
    case ${cmd} in
      1)
        echo "${cafe} AutoLocalPrivilegeEscalation:$cyan An automated script that download potential exploit for linux kernel from exploitdb, and compile them automatically."
        sh PrivEsc/Linux/AutoLocalPrivilegeEscalation/auto_priv_exploit.sh
        sleep 5
      ;;
      2)
        echo "${cafe}BeRoot ....${nc}"
        python PrivEsc/Linux/BeRoot/Linux/beroot.py
        sleep 5
      ;;
      3)
        echo "${cafe}LinEnum ....${nc}"
        sh PrivEsc/Linux/Enumeration/LinEnum.sh
        sleep 5
      ;;
      4)
        echo "${cafe}LinPEAS ....${nc}"
        sleep 5
      ;;
      5)
        echo "${cafe}Linux Priviledge Checker ....${nc}"
        sleep 5
      ;;
      6)
        echo "${cafe}Linux Smart Enumeratin ....${nc}"
        sleep 5
      ;;
      7)
        echo "${cafe}Macgic Recon ....${nc}"
        sleep 5
      ;;
      8)
        echo "${cafe}Expliot Suggester ....${nc}"
        sleep 5
      ;;
      9)
        echo "${cafe}Exiting ....${nc}"
        sleep 5
      ;;
      10)
        echo "${cafe}Exiting ....${nc}"
        sleep 5
      ;;
      11)
        echo "${cafe}Exiting ....${nc}"
        sleep 5
      ;;
      12)
        echo "${cafe}AutoLocalPrivilegeEscalation ....${nc}"
      ;;
      13)
        echo "${cafe}BeRoot ....${nc}"
        # python PrivEsc/Linux/Enumeration/SUID3NUM/suid3num.py
      ;;
      14)
        echo "${cafe}LinEnum ....${nc}"
      ;;
      15)
        echo "${cafe}LinPEAS ....${nc}"
        sleep 5
      ;;
      16)
        echo "${cafe}Linux Priviledge Checker ....${nc}"
        sleep 5
      ;;
      17)
        echo "${cafe}Linux Smart Enumeratin ....${nc}"
        sleep 5
      ;;
      18)
        echo "${cafe}Macgic Recon ....${nc}"
        sleep 5
      ;;
      0|00|x|exit|Exit)
        echo "${cafe}Exiting ....${nc}"
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!${nc}"
        sleep 1
      ;;
    esac
  done
}


# install tools
install() {
  # get tool alias name
  tool_name=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f1`
  # get tool package manager
  tool_installer=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`grep '.' $tools_data | sort -f | sed -n "$1p" | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url ~/$tool_name
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url ~/$tool_name
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${purple}'$tool_name' ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
  # wait for user any input
  echo "$prompt "
  read tmp_inp
}

# install category tools
install_category_tool() {
  # get tool alias name
  tool_name=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f1`
  # get tools package manager
  tool_installer=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`grep '.' $tools_data | sort -f | sed -n "/$1/p" | sed -n "$2 p" | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: '$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
  # wait for user any input
  echo "$prompt "
  read tmp_inp
}

# list all tools from data
all_tools() {
  while true; do
    clear
    # get all tools data
    echo " ${red} ___
//___// ${yellow}All Tools
"
    for data in `grep "." $tools_data | sort -f | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
      # display tools name from data
      for tool in $data; do
        echo " ${cafe} $tool" | tr '|' ' ' | tr '@' ' '
      done
    done
    echo " ${cafe} 0 Back"
    echo "$prompt "
    read cmd
    # count total number of tools
    list=`grep -n "." $tools_data | wc -l`
    # process user input
    case ${cmd} in
      [1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9])
        if [ ${cmd} -le $list ]; then
          # install tools
          install ${cmd}
        else
          echo "${red}${cmd}: ${purple}invalid option!!"
          sleep 1
        fi
      ;;
      0|back|Back)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# category function
category() {
  while true; do
    clear
    # get all category data
    echo " ${red} ___
//___// ${yellow}Tool Category
"
    for data in `grep "." $category_data | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
      # display category alias name from data
      for category in $data; do
        echo " ${cafe} $category" | tr '|' ' ' | tr '@' ' '
      done
    done
    echo " ${cafe} 0 Back"
    echo "$prompt "
    read cmd
    # count total number of category
    list=`grep -n "." $category_data | wc -l`
    # process user input
    case ${cmd} in
      [1-9]|[1-9][0-9])
        if [ ${cmd} -le $list ]; then
          while [ true ]; do
            clear
            # display all tools of selected category
            category=`grep '.' $category_data | sed -n "${cmd} p" | cut -d"|" -f2`
            category_alias=`grep '.' $category_data | sed -n "${cmd} p" | cut -d"|" -f1`
            # get all tools data and display
            echo " ${red} ___
//___// ${yellow}$category_alias
"
            for data in `grep "." $tools_data | sort -f | sed -n "/$category/p" | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
              # display tools name from data
              for tool in $data; do
                echo " ${cafe} $tool" | tr '|' ' ' | tr '@' ' '
              done
            done
            echo " ${cafe} 0 Back"
            echo "$prompt "
            read tmp_cmd
            # count total number of tools in category
            list=`grep -n "." $tools_data | sed -n "/$category/p" | wc -l`
            # process user input
            case $tmp_cmd in
              [1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9])
                if [ $tmp_cmd -le $list ]; then
                  # install tools
                  install_category_tool $category $tmp_cmd
                else
                  echo "${red}$tmp_cmd: ${purple}invalid option!!"
                  sleep 1
                fi
              ;;
                0|back|Back)
                break
              ;;
              *)
                echo "${red}'$tmp_cmd': ${purple}invalid option!!"
                sleep 1
              ;;
            esac
          done
        else
          echo "${red}${cmd}: ${purple}invalid option!!"
          sleep 1
        fi
      ;;
      0|back|Back)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# update HacKing function
update() {
  while true; do
    clear
    echo "$logo"
    echo " ${nc}[1] ${cafe} Update${nc}"
    echo " ${nc}[0] ${cafe} Back"
    echo "$prompt "
    read cmd
    case ${cmd} in
      1)
        # check user is online or not
        wget -q --spider http://google.com
        if [ $? -eq 0 ]; then
          echo "${cafe}Updating ...${nc}"
          sleep 1
          if [ `command -v git` ]; then
            if [ $sudo ]; then
              $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              $sudo chmod +x ~/HacKing/install
              $sudo sh ~/HacKing/install
            else
              git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              chmod +x ~/HacKing/install
              sh ~/HacKing/install
            fi
          else
            if [ $sudo ]; then
              $sudo $pac install git -y
              $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              $sudo chmod +x ~/HacKing/install
              $sudo sh ~/HacKing/install
            else
              $pac install git -y
              git clone https://github.com/Anlominus/HacKing.git ~/HacKing
              chmod +x ~/HacKing/install
              sh ~/HacKing/install
            fi
          fi
          echo "${cafe} HacKing updated !!${nc}"
          sleep 1
        else
          echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          sleep 1
        fi
      ;;
      0)
        break
      ;;
      *)
        echo "${red}${cmd}: ${purple}invalid option!!"
        sleep 1
      ;;
    esac
  done
}

# list all tools from data
cli_list_all() {
  # get all tools data
  tool=`grep "." $tools_data | sort -f | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr '|' ' '`
  # display tools name from data
  echo "${cafe} $tool${nc}"
}

# category function
cli_category() {
  # get all category data
  for data in `grep "." $category_data | grep -n '.' | sed -n 's/:/|/p' | cut -d"|" -f1,2 | tr ' ' '@'`; do
    # display category alias name from data
    for category in $data; do
      echo " ${cafe} $category${nc}" | tr '|' ' ' | tr '@' ' '
    done
  done
}

# update process
update_process() {
  # check file is downloaded or not
  if [ -e $home/HacKing/HacKing ]; then
    # removing old one
    if [ -e $bin/HacKing ]; then
      if [ -d $conf_dir/HacKing ]; then
        if [ $sudo ]; then
          $sudo rm -rf $bin/HacKing
          $sudo rm -rf $conf_dir/HacKing
        else
          rm -rf $bin/HacKing
          rm -rf $conf_dir/HacKing
        fi
      fi
    fi
  fi

  # updating HacKing
  if [ -e $home/HacKing/HacKing ]; then
    if [ $sudo ]; then
      $sudo mv -v $home/HacKing/HacKing $bin
      $sudo chmod +x $bin/HacKing
    else
      mv -v $home/HacKing/HacKing $bin
      chmod +x $bin/HacKing
    fi
  fi
  if [ -d $home/HacKing ]; then
    if [ $sudo ]; then
    $sudo mv -v $home/HacKing $conf_dir
    else
      mv -v $home/HacKing $conf_dir
    fi
  fi
}

# update HacKing function
cli_update() {
  # check user is online or not
  wget -q --spider http://google.com
  if [ $? -eq 0 ]; then
    echo "${cafe}Updating ...${nc}"
    sleep 1
    if [ `command -v git` ]; then
      if [ $sudo ]; then
        $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      else
        git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
       fi
    else
      if [ $sudo ]; then
        $sudo $pac install git -y
        $sudo git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      else
        $pac install git -y
        git clone https://github.com/Anlominus/HacKing.git ~/HacKing
        update_process
      fi
    fi
    echo "${nc}'HacKing' ${cafe} updated successfully !!${nc}"
  else
    echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
  fi
}

# cli install process
install_process() {
  # get tool alias name
  tool_name=`echo $1 | cut -d"|" -f1`
  # get tool package manager
  tool_installer=`echo $1 | cut -d"|" -f5`
  # tool dependency (requirements)
  tool_dependency=`echo $1 | cut -d"|" -f6 | tr ' ' ','`
  # tool url
  tool_url=`echo $1 | cut -d"|" -f4`
  # package name or tool name
  tool_pac=`echo $1 | cut -d"|" -f2`

  # check tool name is null or not
  if [ "$tool_name" ]; then

    case $tool_installer in

    # for default package
    package_manager)
      # check tool is already installed or not
      if [ ! `command -v $tool_pac` ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $sudo $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_pac != "" -a $tool_pac != "null" ]; then
              $pac install $tool_pac -y
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! `command -v $tool_pac` ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for github tools
    git)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo git clone $tool_url ./$tool_name
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              git clone $tool_url ./$tool_name
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for curl tools
    curl)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              curl -o "./$tool_pac" $tool_url
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;
    # for wget tools
    wget)
      # check tool is already installed or not
      if [ ! -e "./$tool_pac" ]; then
        # check sudo is null or not
        if [ $sudo ]; then
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            # install tool dependency
            echo "${cafe}Installing ...${nc}"
            sleep 1
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $sudo $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              $sudo wget $tool_url -o "./$tool_pac"
            fi
          else
            echo "${red}Sorry you are offline !!${nc}"
          fi
        else
          #check user is online or not
          wget -q --spider http://google.com
          if [ $? -eq 0 ]; then
            echo "${cafe}Installing ...${nc}"
            sleep 1
            # install tool dependency
            if [ $tool_dependency != "null" ]; then
              for dep_name in `echo $tool_dependency | tr ',' ' '`; do
                # installing dependency
                if [ ! `command -v $dep_name` ]; then
                  $pac install $dep_name -y
                fi
              done
            fi
            # installing tools
            if [ $tool_url != "" -a $tool_url != "null" ]; then
              wget $tool_url -o ""./$tool_pac""
            fi
          else
            echo "${red}Sorry ${nc}: you are ${red} offline ${nc}!!${nc}"
          fi
        fi
        # check tool is installed or not
        if [ ! -e "./$tool_pac" ]; then
          echo "${red}Sorry ${nc}: '$tool_name' ${red} is not installed !!${nc}"
        else
          echo "${nc}'$tool_name' ${nc}: ${cafe} is installed successfully !!${nc}"
        fi
      else
        echo "${red}Sorry ${nc}: ${nc}'$tool_name' ${cafe} is already installed !!${nc}"
      fi
    ;;

    # for any new installer
    # put here
    esac
  fi
}

# check tool is exists or not
cli_install() {
  # get tools data
  for data in `grep -i "^$1" $tools_data`; do
    # display tools name from data
    for tool in $data; do
      # convert to lower case and check tool name
      if [ `echo $tool | cut -d"|" -f1 | tr 'A-Z' 'a-z'` = `echo $1 | tr 'A-Z' 'a-z'` ]; then
        get_tool_data=$tool
      fi
    done
  done
  # check data exists or not
  if [ $get_tool_data ]; then
    install_process $get_tool_data
  else
    echo "${red}Sorry ${nc}: '$1' ${red} tool not found !!${nc}"
    similar=`grep -i "^$1" $tools_data | cut -d"|" -f1`
    if [ "$similar" ]; then
      echo "${blue}Did you mean${nc}:"
      echo -n "${cafe} "
      grep -i "^$1" $tools_data | cut -d"|" -f1
      echo -n "${nc}"
    fi
  fi
}

# search tool
cli_search() {
  # get tools data
  similar=`grep -i "^$1" $tools_data | cut -d"|" -f1`
  if [ "$similar" ]; then
    echo -n "${cafe}"
    grep -i "^$1" $tools_data | cut -d"|" -f1
    echo -n "${nc}"
  else
    echo "${red}Sorry ${nc}: '$1' ${red} tool not found !!${nc}"
  fi
}

# remove function
cli_remove() {
  # add remove tools functionality for remove tools data now it only uninstall HacKing.
  # removing HacKing only
  if [ -e $bin/HacKing ]; then
    if [ -d $conf_dir/HacKing ]; then
      if [ $sudo ]; then
        $sudo rm -rf $bin/HacKing
        $sudo rm -rf $conf_dir/HacKing
      else
        rm -rf $bin/HacKing
        rm -rf $conf_dir/HacKing
      fi
    fi
  fi
  # check HacKing removed or not
  if [ ! -e $bin/HacKing ]; then
    if [ ! -d $conf_dir/HacKing ]; then
      echo "${nc}'HacKing' : ${cafe} uninstalled successfully !!${nc}"
    fi
  fi
}

# cli mode
if [ $# -eq 1 ]; then
  case $1 in
    start)
      menu
    ;;
    list|-l)
      cli_list_all
    ;;
    update|-u)
      cli_update
    ;;
    remove|-r)
      cli_remove
    ;;
    help|-h)
      echo "${yellow}HacKing ${red} v0.1"
      echo "${nc}Usage ${nc}: ${yellow} HacKing ${nc}[option]... [toolname]...${nc}"
      echo "\n  ${blue}Option  \tDescription${nc}"
      echo "  -----------  \t--------------------"
      echo "  help, -h  \tdisplay this help."
      echo "  list, -l  \tlist all tools."
      echo "  list -a  \tlist all tools."
      echo "  -l a  \tlist all tools."
      echo "  install, -i  \tinstall any tools."
      echo "  search, -s  \tsearch tools."
      echo "  update, -u  \tupdate HacKing."
      echo "  start  \tstart HacKing menu mode."
    ;;
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
    ;;
  esac
elif [ $# -eq 2 ]; then
  case $1 in
    list|-l)
      case $2 in
        -a|a)
          cli_list_all
         ;;
        *)
          echo "${red}Sorry ${nc}: '$2' ${red} invalid option!!${nc}"
          echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
        ;;
      esac
    ;;
    install|-i)
      cli_install $2
    ;;
    search|-s)
      cli_search $2
    ;;
    *)
      echo "${red}Sorry ${nc}: '$1' ${red} invalid option!!${nc}"
      echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
    ;;
  esac
else
  echo "${blue}type ${nc}:\n  'HacKing -h' or 'HacKing help' for help.${nc}"
fi
