#!/bin/bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
#
# [1]  AnonSurf
# [2]  Forensics
# [3]  FramXploit
# [4]  HasHack
# [5]  InfoGath
# [6]  PayLoads
# [7]  PhisHack
# [8]  PrivEsc
# [9]  RemoteAccess
# [10]  ReversEngine
# [11]  Steganograhy
# [12]  VulnHack
# [13]  WebHack
# [14]  WireLess
# [15]  XInstKits
#
################
#    VColors   #
################
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
nc=""

###############
#    Banner   #
###############
function Banner(){
echo ""
echo ""
echo "$red       ###############################################"
echo "       #     _   _            _  ___                 #"
echo "       #    | | | | __ _  ___| |/ (_)_ __   __ _     #"
echo "       #    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #"
echo "       #    |  _  | (_| | (__| . \| | | | | (_| |    #"
echo "       #    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #"
echo "       #                                   |___/     #"
echo "$red       ###############################################"
echo "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]\n"
}
##################
#    ManBanner   #
##################
function ManBanner(){
echo -e "$purple
                           .
                       ..',,'..
                     .',,,,,,,,,.
                    .',,,'..',,,,'.
                   .',,'.     .,,,'
                  .',,.        .,,,.
                 .',..           .,,.
                 .'.              ..,.
                 .                  .'
                ..    $green Aภl๏miuภuຮ $purple   .
                ..                   .
                ..                  ...
         ....''''.     $blue HacKing$purple     .','''....
       .',,,,,,,,'..               ..',,,,,,,,'.
      ...'',,,,,,,'...          ....',,,,,,,,'...
     ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
    ......'',,;;;:::cccllllooooooooooooollll:'.....
    .....'.'',,;;::ccloodxxxdddddddooooollll,.'....
    .......',,;;::clloddxkkkkxxxdddoooollllc,......
    .'''''',,;;::cclooooDATOS0000Oxoooollllc,.......
   ..'''',',;;::ccclllooodk0xdddddxdoollllcc,'''''...
  ........';;::ccclllooodddxkkkkkkxdollllcc:'.........
 ......  .':::ccllloooodddxxxddddoddolllcc::'..  ......
 ......:.;:::ccllloooodddxxxddddooooollcc::;'c,':......
  .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''.
"
echo -e "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]"
}
##################
#    Variables   #
##################
nx="X"
nq="Q"
na="A"
nb="ab"
n00="00"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n7="7"
n8="8"
n9="9"
n10="10"
n11="11"
n12="12"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"
##################
#    VCOLOR     #
##################
uSage="$red[$cyan USAGE $red]$blue"
currentDir="$red[$grey Current Dir $red]$cyan"
installingDir="$red[$grey Installing Dir $red]$cyan"
cSharp="$red[$yellow#$red]$white"
cInfo="$red[$yellow!$red]$yellow"
cPlus="$red[$green+$red]$white"
cx="$red[$green$nx$red]$cafe"
cq="$red[$green$nq$red]$cafe"
ca="$red[$green$na$red]$cafe"
cb="$red[$green$nb$red]$cafe"
c1="$red[$green$n1$red]$cafe"
c2="$red[$green$n2$red]$cafe"
c3="$red[$green$n3$red]$cafe"
c4="$red[$green$n4$red]$cafe"
c5="$red[$green$n5$red]$cafe"
c6="$red[$green$n6$red]$cafe"
c7="$red[$green$n7$red]$cafe"
c8="$red[$green$n8$red]$cafe"
c9="$red[$green$n9$red]$cafe"
c10="$red[$green$n10$red]$cafe"
c11="$red[$green$n11$red]$cafe"
c12="$red[$green$n12$red]$cafe"
c13="$red[$green$n13$red]$cafe"
c14="$red[$green$n14$red]$cafe"
c15="$red[$green$n15$red]$cafe"
c16="$red[$green$n16$red]$cafe"
c17="$red[$green$n17$red]$cafe"
c18="$red[$green$n18$red]$cafe"
##########Prompt##########
promptOption="\n\t${purple}[${blue} Anlominus ${cyan}@${blue} HacKing ${purple}]  $ $green"
##########Prompt##########

#######################
chmod 777  HacKing
#######################

#######################
#   Start: Functions  #
#######################
start(){
  echo "$cInfo Starting HacKingPro"
  sleep 1
  cd HacKingPro
  chmod 777 HacKingPro
  sh HacKingPro
  cd ../
  break
}

install(){
  Echo "Current Directory"
  echo "\t$installingDir $(pwd)"
  sleep 1
  echo "$cSharp Installing HacKingPro"
  sleep 1
  echo "$cInfo Creating $grey HacKingPro"
  sleep 1
  mkdir HacKingPro 2> /dev/null
  echo "$cInfo Creating $grey AnonSurf"
  sleep 1
  mkdir HacKingPro/AnonSurf  2> /dev/null
  echo "$cInfo Creating $grey Forensics"
  sleep 1
  mkdir HacKingPro/Forensics 2> /dev/null
  echo "$cInfo Creating $grey FramXploit"
  sleep 1
  mkdir HacKingPro/FramXploit 2> /dev/null
  echo "$cInfo Creating $grey HasHack"
  sleep 1
  mkdir HacKingPro/HasHack 2> /dev/null
  echo "$cInfo Creating $grey InfoGath"
  sleep 1
  mkdir HacKingPro/InfoGath 2> /dev/null
  echo "$cInfo Creating $grey PayLoads"
  sleep 1
  mkdir HacKingPro/PayLoads 2> /dev/null
  echo "$cInfo Creating $grey PhisHack"
  sleep 1
  mkdir HacKingPro/PhisHack 2> /dev/null
  echo "$cInfo Creating $grey PrivEsc"
  sleep 1
  mkdir HacKingPro/PrivEsc 2> /dev/null
  echo "$cInfo Creating $grey RemoteAccess"
  sleep 1
  mkdir HacKingPro/RemoteAccess 2> /dev/null
  echo "$cInfo Creating $grey ReversEngine"
  sleep 1
  mkdir HacKingPro/ReversEngine 2> /dev/null
  echo "$cInfo Creating $grey Steganograhy"
  sleep 1
  mkdir HacKingPro/Steganograhy 2> /dev/null
  echo "$cInfo Creating $grey VulnHack"
  sleep 1
  mkdir HacKingPro/VulnHack 2> /dev/null
  echo "$cInfo Creating $grey WebHack"
  sleep 1
  mkdir HacKingPro/WebHack 2> /dev/null
  echo "$cInfo Creating $grey WireLess"
  sleep 1
  mkdir HacKingPro/WireLess 2> /dev/null
  echo "$cInfo Creating $grey XInstKits"
  sleep 1
  mkdir HacKingPro/XInstKits 2> /dev/null
  echo "$cInfo Copying WorKing into$blue HacKingPro"
  sleep 1
  cp WorKing ./HacKingPro
  echo "$cInfo Renaming WorKing to$blue HacKingPro"
  sleep 1
  mv HacKingPro/WorKing HacKingPro/HacKingPro
  echo "$cInfo Giving all permission to$blue HacKingPro"
  sleep 1
  chmod 777 HacKingPro/HacKingPro  2> /dev/null
  echo "$cInfo Start$blue HacKingPro"
  sleep 5
  start
}

remove(){
  echo "$cInfo Removing HacKingPro"
  sleep 3
  rm -r ./HacKingPro*
  touch RemovedSuccess
  echo "#!/bin/bash" > RemovedSuccess
  echo "echo Removing Sucessfully!" > RemovedSuccess
  bash RemovedSuccess
}

usage(){
  echo "
  $uSage bash HacKing start
  $uSage bash HacKing install
  $uSage bash HacKing remove
  "
}

main(){
  Banner
  usage
  echo "\t$cInfo Please select an action $cInfo\n"
  echo "\t ${c1} ${cafe} Start "
  echo "\t ${c2} ${cafe} Install "
  echo "\t ${c3} ${cafe} Remove "
  echo "\t ${cq} ${cafe} Quit to Main Menu "
  echo ""
  echo "\t$currentDir $(pwd)"
  echo "  $promptOption "
	read -p "Enter Choice: " choice
	if [[ $choice == '1' ]]; then start; fi
	if [[ $choice == '2' ]]; then install; fi
	if [[ $choice == '3' ]]; then remove; fi
	if [[ $choice == 'Q' || $choice == 'q' ]] ; then
		echo "$cInfo Quit to Main Menu"
		clear && exit
	fi
    echo "$cInfo Returning to main menu..."
    clear && main

}
######################
#   End: Functions   #
######################

######################
#   Start: Options   #
######################
if [ "$1" == "start" ]; then
    start
elif [ "$1" == "install" ]; then
    install
elif [ "$1" == "remove" ]; then
    remove
else
    main
fi
####################
#   End: Options   #
####################
