#!/usr/bin/env bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
# Name : HacKing
# Date : 1 November 2021
# Description : HacKing is a hacking tools installer and package manager for hacker's.
#
# New Name : HacKing
# New Date : 10 January 2022
# New Description : HacKing is a hacking tools installer and package manager for hacker's.
#
# Created: 10/01/2022
# Aouther: Global Anlominus RhytMix 2022
# Skils: Best Copyrigter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: ToAllWorldCreatorsHackingTools
# Location: Made With Love IN Israel
# Tool Name: HacKing
# Source: https://github.com/Anlominus/HacKing
#
###############
#    Banner   #
###############
function Banner(){
echo ""
echo ""
echo "$red       ###############################################"
echo "       #     _   _            _  ___                 #"
echo "       #    | | | | __ _  ___| |/ (_)_ __   __ _     #"
echo "       #    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #"
echo "       #    |  _  | (_| | (__| . \| | | | | (_| |    #"
echo "       #    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #"
echo "       #                                   |___/     #"
echo "$red       ###############################################"
echo "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]\n\n"

}

##################
#    ManBanner   #
##################
function ManBanner(){
echo -e "$purple
                           .
                       ..',,'..
                     .',,,,,,,,,.
                    .',,,'..',,,,'.
                   .',,'.     .,,,'
                  .',,.        .,,,.
                 .',..           .,,.
                 .'.              ..,.
                 .                  .'
                ..    $green Aภl๏miuภuຮ $purple   .
                ..                   .
                ..                  ...
         ....''''.     $blue HacKing$purple     .','''....
       .',,,,,,,,'..               ..',,,,,,,,'.
      ...'',,,,,,,'...          ....',,,,,,,,'...
     ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
    ......'',,;;;:::cccllllooooooooooooollll:'.....
    .....'.'',,;;::ccloodxxxdddddddooooollll,.'....
    .......',,;;::clloddxkkkkxxxdddoooollllc,......
    .'''''',,;;::cclooooDATOS0000Oxoooollllc,.......
   ..'''',',;;::ccclllooodk0xdddddxdoollllcc,'''''...
  ........';;::ccclllooodddxkkkkkkxdollllcc:'.........
 ......  .':::ccllloooodddxxxddddoddolllcc::'..  ......
 ......:.;:::ccllloooodddxxxddddooooollcc::;'c,':......
  .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''.
"
echo -e "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]"
}

nc="\033[00m"
################
#    VColors   #
################
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
nc=""


# checking for system home dir
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

# checking for system bin dir
if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

# checking for configuration dir
if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

# configuration files
if [ -d $conf_dir/HacKing ]; then
  if [ -e $conf_dir/HacKing/data/tools.dat ]; then
    tools_data="$conf_dir/HacKing/data/tools.dat"
  fi
  if [ -e $conf_dir/HacKing/data/category.dat ]; then
    category_data="$conf_dir/HacKing/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

# checking for system root access
if [ `command -v sudo` ]; then
  sudo="sudo"
else
  sudo=""
fi

# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
  sudo=""
fi

# setup process
clear
echo "$logo"
echo "${green} Installing .... ${nc}"
sleep 1
echo "${yellow} Running setup .... ${nc}"
sleep 1

# installing dependency
for each_pac in "wget" "curl" "git"; do
  if [ ! `command -v $each_pac` ]; then
    if [ $sudo ]; then
      $sudo $pac install $each_pac -y
    else
      $pac install $each_pac -y
    fi
  fi
done

# removing old one
if [ -e $bin/HacKing ]; then
  if [ -d $conf_dir/HacKing ]; then
    if [ $sudo ]; then
      $sudo rm -rf $bin/HacKing
      $sudo rm -rf $conf_dir/HacKing
    else
      rm -rf $bin/HacKing
      rm -rf $conf_dir/HacKing
    fi
  fi
fi

# install HacKing
if [ $0 = "install" -o $0 = "./install" ]; then
  if [ -e HacKing ]; then
    if [ $sudo ]; then
      $sudo mv -v HacKing $bin
      $sudo chmod +x $bin/HacKing
    else
      mv -v HacKing $bin
      chmod +x $bin/HacKing
    fi
  fi
  cd ..
  if [ -d HacKing ]; then
    if [ $sudo ]; then
    $sudo mv -v HacKing $conf_dir
    else
      mv -v HacKing $conf_dir
    fi
  fi
else
  if [ -e HacKing/HacKing ]; then
    if [ $sudo ]; then
      $sudo mv -v HacKing/HacKing $bin
      $sudo chmod +x $bin/HacKing
    else
      mv -v HacKing/HacKing $bin
      chmod +x $bin/HacKing
    fi
  fi
  if [ -d HacKing ]; then
    if [ $sudo ]; then
    $sudo mv -v HacKing $conf_dir
    else
      mv -v HacKing $conf_dir
    fi
  fi
fi

# check HacKing is installed or not
if [ -e $bin/HacKing ]; then
  if [ -d $conf_dir/HacKing ]; then
    clear
    echo "$logo"
    echo " ${purple}HacKing ${green}installed successfully !!"
    echo " ${green}type ${nc}'HacKing -h'${green} for more.${nc}"
  else
    clear
    echo "$logo"
    echo " ${red}Sorry ${cyan}: HacKing ${red}is not installed !!"
    echo " ${green}Please try again${nc}"
  fi
fi
