#!/bin/bash
###############################################
#     _   _            _  ___                 #
#    | | | | __ _  ___| |/ (_)_ __   __ _     #
#    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #
#    |  _  | (_| | (__| . \| | | | | (_| |    #
#    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #
#                                   |___/     #
###############################################
#
# [1]  AnonSurf
# [2]  Forensics
# [3]  FramXploit
# [4]  HasHack
# [5]  InfoGath
# [6]  PayLoads
# [7]  PhisHack
# [8]  PrivEsc
# [9]  RemoteAccess
# [10]  ReversEngine
# [11]  Steganograhy
# [12]  VulnHack
# [13]  WebHack
# [14]  WireLess
# [15]  XInstKits
#
################
#    VColors   #
################
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
purple="\033[0;35m"
cyan="\033[0;36m"
cafe="\033[0;33m"
fiuscha="\033[0;35m"
blue="\033[1;34m"
nc=""
###############
#    Banner   #
###############
function Banner(){
echo ""
echo ""
echo "$red       ###############################################"
echo "       #     _   _            _  ___                 #"
echo "       #    | | | | __ _  ___| |/ (_)_ __   __ _     #"
echo "       #    | |_| |/ _' |/ __| ' /| | '_ \ / _' |    #"
echo "       #    |  _  | (_| | (__| . \| | | | | (_| |    #"
echo "       #    |_| |_|\__,_|\___|_|\_\_|_| |_|\__, |    #"
echo "       #                                   |___/     #"
echo "$red       ###############################################"
echo "  $red[$green+$red]$cyan https://www.github.com/Anlominus $red[$green+$red]\n"
}
##################
#    ManBanner   #
##################
function ManBanner(){
echo "$purple
                           .
                       ..',,'..
                     .',,,,,,,,,.
                    .',,,'..',,,,'.
                   .',,'.     .,,,'
                  .',,.        .,,,.
                 .',..           .,,.
                 .'.              ..,.
                 .                  .'
                ..    $green Aภl๏miuภuຮ $purple   .
                ..                   .
                ..                  ...
         ....''''.     $blue HacKing$purple     .','''....
       .',,,,,,,,'..               ..',,,,,,,,'.
      ...'',,,,,,,'...          ....',,,,,,,,'...
     ....'',;;;;;;;,,'''......'''',,;;;;;;;,'''...
    ......'',,;;;:::cccllllooooooooooooollll:'.....
    .....'.'',,;;::ccloodxxxdddddddooooollll,.'....
    .......',,;;::clloddxkkkkxxxdddoooollllc,......
    .'''''',,;;::cclooooDATOS0000Oxoooollllc,.......
   ..'''',',;;::ccclllooodk0xdddddxdoollllcc,'''''...
  ........';;::ccclllooodddxkkkkkkxdollllcc:'.........
 ......  .':::ccllloooodddxxxddddoddolllcc::'..  ......
 ......:.;:::ccllloooodddxxxddddooooollcc::;'c,':......
  .''..cc.''''''',,,,,,,;;;;;,,,,,,,,''''....:.cc..''.
"
echo "  $red[$green+$red]$cyan Github: https://www.github.com/Anlominus/HacKing $red[$green+$red]"
}
##################
#    Variables   #
##################
nx="X"
nq="Q"
na="A"
nb="ab"
n00="00"
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n7="7"
n8="8"
n9="9"
n10="10"
n11="11"
n12="12"
n13="13"
n14="14"
n15="15"
n16="16"
n17="17"
n18="18"
##################
#    VCOLOR     #
##################
uSage="$red[$cyan USAGE $red]$blue"
currentDir="$red[$grey Current Dir $red]$cyan "
installingDir="$red[$grey Installing Dir $red]$cyan"
cSharp="$red[$yellow#$red]$white"
cInfo="$red[$yellow!$red]$yellow"
cPlus="$red[$green+$red]$white"
cx="$red[$green$nx$red]$cafe"
cq="$red[$green$nq$red]$cafe"
ca="$red[$green$na$red]$cafe"
cb="$red[$green$nb$red]$cafe"
c1="$red[$green$n1$red]$cafe"
c2="$red[$green$n2$red]$cafe"
c3="$red[$green$n3$red]$cafe"
c4="$red[$green$n4$red]$cafe"
c5="$red[$green$n5$red]$cafe"
c6="$red[$green$n6$red]$cafe"
c7="$red[$green$n7$red]$cafe"
c8="$red[$green$n8$red]$cafe"
c9="$red[$green$n9$red]$cafe"
c10="$red[$green$n10$red]$cafe"
c11="$red[$green$n11$red]$cafe"
c12="$red[$green$n12$red]$cafe"
c13="$red[$green$n13$red]$cafe"
c14="$red[$green$n14$red]$cafe"
c15="$red[$green$n15$red]$cafe"
c16="$red[$green$n16$red]$cafe"
c17="$red[$green$n17$red]$cafe"
c18="$red[$green$n18$red]$cafe"
##########Prompt##########
promptOption="\n\t${purple}[${blue} Anlominus ${cyan}@${blue} HacKing ${purple}]  $ $green"
##########Prompt##########

#######################
chmod 777  WorKing
#######################

#   Functions  #
######Tools######
AnonSurf(){
  echo ""
  cd AnonSurf
  echo "\t$currentDir $(pwd)"
}
Forensics(){
  echo ""
  cd Forensics
  echo "\t$currentDir $(pwd)"
}
FramXploit(){
  echo ""
  cd FramXploit
  echo "\t$currentDir $(pwd)"
}
HasHack(){
  echo ""
  cd HasHack
  echo "\t$currentDir $(pwd)"
}
InfoGath(){
  echo ""
  cd InfoGath
  echo "\t$currentDir $(pwd)"
}
PayLoads(){
  echo ""
  cd PayLoads
  echo "\t$currentDir $(pwd)"
}
PhisHack(){
  echo ""
  cd PhisHack
  echo "\t$currentDir $(pwd)"
}
PrivEsc(){
  echo ""
  cd PrivEsc
  echo "\t$currentDir $(pwd)"
}
RemoteAccess(){
  echo ""
  cd RemoteAccess
  echo "\t$currentDir $(pwd)"
}
ReversEngine(){
  echo ""
  cd ReversEngine
  echo "\t$currentDir $(pwd)"
}
Steganograhy(){
  echo ""
  cd Steganograhy
  echo "\t$currentDir $(pwd)"
}
VulnHack(){
  echo ""
  cd VulnHack
  echo "\t$currentDir $(pwd)"
}
WebHack(){
  echo ""
  cd WebHack
  echo "\t$currentDir $(pwd)"
}
WireLess(){
  echo ""
  cd WireLess
  echo "\t$currentDir $(pwd)"
}
XInstKits(){
  echo ""
  cd XInstKits
  echo "\t$currentDir $(pwd)"
}
######Tools######
######MainMenu######
main(){
  ManBanner
  echo "\t$cInfo Please select an action $cInfo\n"
  echo "\t ${c1} ${cafe} AnonSurf"
  echo "\t ${c2} ${cafe} Forensics"
  echo "\t ${c3} ${cafe} FramXploit"
  echo "\t ${c4} ${cafe} HasHack"
  echo "\t ${c5} ${cafe} InfoGath"
  echo "\t ${c6} ${cafe} PayLoads"
  echo "\t ${c7} ${cafe} PhisHack"
  echo "\t ${c8} ${cafe} PrivEsc"
  echo "\t ${c9} ${cafe} RemoteAccess"
  echo "\t ${c10} ${cafe} ReversEngine"
  echo "\t ${c11} ${cafe} Steganograhy"
  echo "\t ${c12} ${cafe} VulnHack"
  echo "\t ${c13} ${cafe} WebHack"
  echo "\t ${c14} ${cafe} WireLess"
  echo "\t ${c15} ${cafe} XInstKits"
  echo "\t ${cq} ${cafe} Quit to Main Menu "
  echo ""
  echo "\t$currentDir $(pwd)"
  echo "  $promptOption " && read -p ":" choice
	if [[ $choice == '1' ]]; then AnonSurf; fi
	if [[ $choice == '2' ]]; then Forensics; fi
	if [[ $choice == '3' ]]; then FramXploit; fi
	if [[ $choice == '4' ]]; then HasHack; fi
	if [[ $choice == '5' ]]; then InfoGath; fi
	if [[ $choice == '6' ]]; then PayLoads; fi
	if [[ $choice == '7' ]]; then PhisHack; fi
	if [[ $choice == '8' ]]; then PrivEsc; fi
	if [[ $choice == '9' ]]; then RemoteAccess; fi
	if [[ $choice == '10' ]]; then ReversEngine; fi
	if [[ $choice == '11' ]]; then Steganograhy; fi
  if [[ $choice == '12' ]]; then VulnHack; fi
  if [[ $choice == '13' ]]; then WebHack; fi
  if [[ $choice == '14' ]]; then WireLess; fi
  if [[ $choice == '15' ]]; then XInstKits; fi
	if [[ $choice == 'Q' || $choice == 'q' ]] ; then
		echo "$cInfo Quit to Main Menu"
    clear
    exit
	fi
    echo "$cInfo Returning to main menu..."
    sleep 0.3
    clear && main
}
######MainMenu######
#   Functions   #

#   Options   #
if [ "$1" == "start" ]; then
    start
elif [ "$1" == "install" ]; then
    install
elif [ "$1" == "remove" ]; then
    remove
else
  main
fi
#   Options   #
